version : '3'
services:
  mariadb:
      build:
        context: ./requirements/mariadb/
      volumes:
        - database:/var/lib/mysql
      restart : always
      container_name : mariadb
      networks:
        - inception
      init : true
      env_file:
        - ./.env

  wordpress:
      build:
        context: ./requirements/wordpress/
      restart : always
      volumes:
        - site:/var/www/html
      container_name : wordpress
      networks:
        - inception
      depends_on :
        - mariadb
      init : true
      env_file:
        - ./.env
  nginx:
      build:
          context: ./requirements/nginx/
      restart : always
      volumes:
        - site:/var/www/html
      container_name : nginx
      depends_on :
        - wordpress
      ports:
        - 443:443
        - 80:80
      networks:
        - inception
      init : true
      env_file:
        - ./.env
volumes:
  database:
      driver: local
      driver_opts:
        type: none
        device: /home/mokhalil/data/dbvol
        o: bind
  site:
    driver: local
    driver_opts:
      type: none
      device: /home/mokhalil/data/wpvol
      o: bind
networks:
  inception:
    name: inception
    driver: bridge