version : '3'
services:
  mariadb:
      build:
        context: ./src/requirements/mariadb/
      volumes:
        - database:/var/lib/mysql
      restart : always
      container_name : mariadb
      environment:
        MYSQL_DATABASE: db
        MYSQL_USER: db_user
        MYSQL_PASSWORD: user_passwd
        MYSQL_ROOT_PASSWORD: 'root_passwd'
        MYSQL_ALLOW_EMPTY_PASSWORD: 0
      networks:
        - inception
      init : true

  wordpress:
      build:
        context: ./src/requirements/wordpress/
      volumes:
        - ./site:/var/www/html
      container_name : wordpress
      environment:
        WORDPRESS_DB_HOST: mariadb
        WORDPRESS_DB_NAME: db
        WORDPRESS_DB_USER: db_user
        WORDPRESS_DB_PASSWORD: user_passwd
      networks:
        - inception
      depends_on :
        - mariadb
      init : true
  nginx:
      build:
          context: ./src/requirements/nginx/
      volumes:
        - ./site:/var/www/html
      container_name : nginx
      depends_on :
        - wordpress
      ports:
        - 443:443
        - 80:80
      networks:
        - inception
      init : true

volumes:
  database:
  site:
networks:
  inception: