version : '3'
services:
  mariadb:
      build:
        contexte: ./src/requerements/mariadb/
      volumes:
        - database:/var/lib/mysql
      restart : always
      container_name : mariadb
      environment:
        MYSQL_ROOT_PASSWORD:
        MYSQL_DATABASE:
        MYSQL_USER:
        MYSQL_PASSWORD:
        MYSQL_ALLOW_EMPTY_PASSWORD:
      network:

      ports:
        - 3306:3306
  wordpress:
      build:
        contexte: ./src/requerements/wordpress/
      volumes:
        - site:/var/www/html
      container_name : wordpress
      depends_on : mariadb
      ports:
        - 8080:80
      environment:
        WORDPRESS_DB_HOST:
        WORDPRESS_DB_NAME:
        WORDPRESS_DB_USER:
        WORDPRESS_DB_PASSWORD:
      linls:
        - mariadb
  nginx:
      build:
          contexte: ./src/requerements/nginx/
      volumes:
      container_name : 
  init: true

volumes:
  database: {}
  site:
networks:
  inception: